import 'package:flutter/material.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/Generated423pmWidget2.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedBatterythreequartersWidget2.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedCows1Widget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedRecordsWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedSignalWidget2.dart';
import 'package:flutterapp/mmaziwaappapp/generatedhomepagewidget/generated/GeneratedWifiWidget2.dart';

/* Frame Homepage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 182.0,
            child: GeneratedRectangle1Widget2(),
          ),
          Positioned(
            left: 8.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 21.0,
            child: T423pmWidget2(),
          ),
          Positioned(
            left: 260.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedSignalWidget2(),
          ),
          Positioned(
            left: 328.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedBatterythreequartersWidget2(),
          ),
          Positioned(
            left: 292.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedWifiWidget2(),
          ),
          Positioned(
            left: 20.0,
            top: 32.0,
            right: null,
            bottom: null,
            width: 320.0,
            height: 135.0,
            child: GeneratedCows1Widget1(),
          ),
          Positioned(
            left: 26.0,
            top: 208.0,
            right: null,
            bottom: null,
            width: 138.0,
            height: 83.0,
            child: GeneratedButtonWidget2(),
          ),
          Positioned(
            left: 179.0,
            top: 208.0,
            right: null,
            bottom: null,
            width: 138.0,
            height: 90.0,
            child: GeneratedButtonWidget3(),
          ),
          Positioned(
            left: 32.0,
            top: 320.0,
            right: null,
            bottom: null,
            width: 298.0,
            height: 37.0,
            child: GeneratedRecordsWidget1(),
          ),
          Positioned(
            left: 99.0,
            top: 603.0,
            right: null,
            bottom: null,
            width: 151.0,
            height: 26.0,
            child: GeneratedButtonWidget4(),
          )
        ]),
      ),
    ));
  }
}
