import 'package:flutter/material.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedEnterthecowstypeWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedEntertodaysmilkbuyerWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedSignalWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedFillthespacestorecordyourcowsdetailsWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedBatterythreequartersWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedEnteramountpaidforthemilksaleWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedEntertheCowsnameWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedEnterthedaysmilkoutputWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedWifiWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/Generated423pmWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedrecordswidget/generated/GeneratedButtonWidget1.dart';

/* Frame Records
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecordsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 29.0,
            child: GeneratedRectangle1Widget1(),
          ),
          Positioned(
            left: 8.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 21.0,
            child: Generated423pmWidget1(),
          ),
          Positioned(
            left: 260.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedSignalWidget1(),
          ),
          Positioned(
            left: 328.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedBatterythreequartersWidget1(),
          ),
          Positioned(
            left: 292.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedWifiWidget1(),
          ),
          Positioned(
            left: 19.0,
            top: 63.0,
            right: null,
            bottom: null,
            width: 324.0,
            height: 38.0,
            child: GeneratedFillthespacestorecordyourcowsdetailsWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 115.0,
            right: null,
            bottom: null,
            width: 266.0,
            height: 30.0,
            child: GeneratedEntertheCowsnameWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 137.0,
            right: null,
            bottom: null,
            width: 287.0,
            height: 28.0,
            child: GeneratedRectangle18Widget(),
          ),
          Positioned(
            left: 24.0,
            top: 179.0,
            right: null,
            bottom: null,
            width: 285.0,
            height: 29.0,
            child: GeneratedEnterthecowstypeWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 205.0,
            right: null,
            bottom: null,
            width: 287.0,
            height: 28.0,
            child: GeneratedRectangle19Widget(),
          ),
          Positioned(
            left: 24.0,
            top: 247.0,
            right: null,
            bottom: null,
            width: 281.0,
            height: 30.0,
            child: GeneratedEnterthedaysmilkoutputWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 272.0,
            right: null,
            bottom: null,
            width: 287.0,
            height: 32.0,
            child: GeneratedRectangle20Widget(),
          ),
          Positioned(
            left: 24.0,
            top: 320.0,
            right: null,
            bottom: null,
            width: 257.0,
            height: 35.0,
            child: GeneratedEntertodaysmilkbuyerWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 345.0,
            right: null,
            bottom: null,
            width: 287.0,
            height: 31.0,
            child: GeneratedRectangle21Widget(),
          ),
          Positioned(
            left: 24.0,
            top: 389.0,
            right: null,
            bottom: null,
            width: 278.0,
            height: 33.0,
            child: GeneratedEnteramountpaidforthemilksaleWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 416.0,
            right: null,
            bottom: null,
            width: 287.0,
            height: 31.0,
            child: GeneratedRectangle22Widget(),
          ),
          Positioned(
            left: 99.0,
            top: 468.0,
            right: null,
            bottom: null,
            width: 162.0,
            height: 52.0,
            child: GeneratedButtonWidget1(),
          )
        ]),
      ),
    ));
  }
}
