import 'package:flutter/material.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedButtonWidget8.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedWifiWidget5.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedCows1Widget2.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedBatterythreequartersWidget5.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedMMaziwaisanapplicationwhichdigitizesyourmilkrecordingst.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedMMaziwaappWidget2.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/Generated423pmWidget5.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedSignalWidget5.dart';
import 'package:flutterapp/mmaziwaappapp/generatedsplashscreenwidget/generated/GeneratedRectangle1Widget5.dart';

/* Frame Splashscreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 434.0,
            child: GeneratedRectangle1Widget5(),
          ),
          Positioned(
            left: 8.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 21.0,
            child: Generated423pmWidget5(),
          ),
          Positioned(
            left: 260.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedSignalWidget5(),
          ),
          Positioned(
            left: 328.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedBatterythreequartersWidget5(),
          ),
          Positioned(
            left: 292.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedWifiWidget5(),
          ),
          Positioned(
            left: 20.0,
            top: 32.0,
            right: null,
            bottom: null,
            width: 320.0,
            height: 135.0,
            child: GeneratedCows1Widget2(),
          ),
          Positioned(
            left: 8.0,
            top: 210.0,
            right: null,
            bottom: null,
            width: 311.0,
            height: 57.0,
            child: GeneratedMMaziwaappWidget2(),
          ),
          Positioned(
            left: 20.0,
            top: 294.0,
            right: null,
            bottom: null,
            width: 322.0,
            height: 101.0,
            child:
                GeneratedMMaziwaisanapplicationwhichdigitizesyourmilkrecordingst(),
          ),
          Positioned(
            left: 71.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 234.0,
            height: 62.0,
            child: GeneratedButtonWidget8(),
          )
        ]),
      ),
    ));
  }
}
