import 'package:flutter/material.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedEnteryourdetailstostartenjotingtheappWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedWifiWidget3.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedButtonWidget6.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedSignalWidget3.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedMMaziwaappWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedEnteryouremailaddressWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedEnteryourpasswordWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/Generated423pmWidget3.dart';
import 'package:flutterapp/mmaziwaappapp/generatedloginwidget/generated/GeneratedBatterythreequartersWidget3.dart';

/* Frame Log in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 132.0,
            child: GeneratedRectangle1Widget3(),
          ),
          Positioned(
            left: 8.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 21.0,
            child: Generated423pmWidget3(),
          ),
          Positioned(
            left: 260.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedSignalWidget3(),
          ),
          Positioned(
            left: 328.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedBatterythreequartersWidget3(),
          ),
          Positioned(
            left: 292.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedWifiWidget3(),
          ),
          Positioned(
            left: 0.0,
            top: 50.0,
            right: null,
            bottom: null,
            width: 311.0,
            height: 57.0,
            child: GeneratedMMaziwaappWidget(),
          ),
          Positioned(
            left: 31.0,
            top: 421.0,
            right: null,
            bottom: null,
            width: 119.0,
            height: 48.0,
            child: GeneratedButtonWidget5(),
          ),
          Positioned(
            left: 27.0,
            top: 105.0,
            right: null,
            bottom: null,
            width: 310.0,
            height: 22.0,
            child: GeneratedEnteryourdetailstostartenjotingtheappWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 234.0,
            right: null,
            bottom: null,
            width: 212.0,
            height: 30.0,
            child: GeneratedEnteryouremailaddressWidget(),
          ),
          Positioned(
            left: 27.0,
            top: 305.0,
            right: null,
            bottom: null,
            width: 211.0,
            height: 31.0,
            child: GeneratedEnteryourpasswordWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 262.0,
            right: null,
            bottom: null,
            width: 317.0,
            height: 33.0,
            child: GeneratedRectangle4Widget(),
          ),
          Positioned(
            left: 24.0,
            top: 332.0,
            right: null,
            bottom: null,
            width: 317.0,
            height: 34.0,
            child: GeneratedRectangle5Widget(),
          ),
          Positioned(
            left: 28.0,
            top: 383.0,
            right: null,
            bottom: null,
            width: 250.0,
            height: 21.0,
            child: GeneratedButtonWidget6(),
          )
        ]),
      ),
    ));
  }
}
