import 'package:flutter/material.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedSignalWidget4.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/Generated423pmWidget4.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedWifiWidget4.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedBatterythreequartersWidget4.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedButtonWidget7.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedMMaziwaappWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedEnteryourfullnamesWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedConfirmpasswordWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedEnteryourpasswordWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedEnteryouremailaddressWidget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/mmaziwaappapp/generatedregistrationwidget/generated/GeneratedWelcomeaboardPleaseregisterwiththisfewstepsWidget.dart';

/* Frame registration
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 132.0,
            child: GeneratedRectangle1Widget4(),
          ),
          Positioned(
            left: 8.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 21.0,
            child: Generated423pmWidget4(),
          ),
          Positioned(
            left: 260.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedSignalWidget4(),
          ),
          Positioned(
            left: 328.0,
            top: 6.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedBatterythreequartersWidget4(),
          ),
          Positioned(
            left: 292.0,
            top: 2.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedWifiWidget4(),
          ),
          Positioned(
            left: 0.0,
            top: 50.0,
            right: null,
            bottom: null,
            width: 311.0,
            height: 57.0,
            child: GeneratedMMaziwaappWidget1(),
          ),
          Positioned(
            left: 27.0,
            top: 105.0,
            right: null,
            bottom: null,
            width: 310.0,
            height: 22.0,
            child: GeneratedWelcomeaboardPleaseregisterwiththisfewstepsWidget(),
          ),
          Positioned(
            left: 19.0,
            top: 165.0,
            right: null,
            bottom: null,
            width: 287.0,
            height: 28.0,
            child: GeneratedEnteryourfullnamesWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 234.0,
            right: null,
            bottom: null,
            width: 212.0,
            height: 30.0,
            child: GeneratedEnteryouremailaddressWidget1(),
          ),
          Positioned(
            left: 19.0,
            top: 375.0,
            right: null,
            bottom: null,
            width: 230.0,
            height: 31.0,
            child: GeneratedConfirmpasswordWidget(),
          ),
          Positioned(
            left: 20.0,
            top: 305.0,
            right: null,
            bottom: null,
            width: 211.0,
            height: 31.0,
            child: GeneratedEnteryourpasswordWidget1(),
          ),
          Positioned(
            left: 24.0,
            top: 192.0,
            right: null,
            bottom: null,
            width: 317.0,
            height: 32.0,
            child: GeneratedRectangle3Widget(),
          ),
          Positioned(
            left: 24.0,
            top: 262.0,
            right: null,
            bottom: null,
            width: 317.0,
            height: 33.0,
            child: GeneratedRectangle4Widget1(),
          ),
          Positioned(
            left: 24.0,
            top: 332.0,
            right: null,
            bottom: null,
            width: 317.0,
            height: 34.0,
            child: GeneratedRectangle5Widget1(),
          ),
          Positioned(
            left: 24.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 317.0,
            height: 38.0,
            child: GeneratedRectangle6Widget(),
          ),
          Positioned(
            left: 30.0,
            top: 456.0,
            right: null,
            bottom: null,
            width: 164.0,
            height: 48.0,
            child: GeneratedButtonWidget7(),
          )
        ]),
      ),
    ));
  }
}
