import 'package:flutter/material.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedLoansandsavingsWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedWithdrawmoneyWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedMyAccountWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedSendMoneyWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedBatterythreequartersWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedBuyairtimeorbundlesWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedCows1Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedSignalWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/Generated423pmWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedMpesaservicesWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedWifiWidget.dart';
import 'package:flutterapp/mmaziwaappapp/generatedmpesawidget/generated/GeneratedLipanaMPesaWidget.dart';

/* Frame M-pesa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMpesaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 2.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 182.0,
              child: GeneratedRectangle1Widget(),
            ),
            Positioned(
              left: 8.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 66.0,
              height: 21.0,
              child: Generated423pmWidget(),
            ),
            Positioned(
              left: 260.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedSignalWidget(),
            ),
            Positioned(
              left: 328.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedBatterythreequartersWidget(),
            ),
            Positioned(
              left: 292.0,
              top: 2.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedWifiWidget(),
            ),
            Positioned(
              left: 20.0,
              top: 32.0,
              right: null,
              bottom: null,
              width: 320.0,
              height: 135.0,
              child: GeneratedCows1Widget(),
            ),
            Positioned(
              left: 23.0,
              top: 207.0,
              right: null,
              bottom: null,
              width: 305.0,
              height: 43.0,
              child: GeneratedRectangle10Widget(),
            ),
            Positioned(
              left: 33.0,
              top: 213.0,
              right: null,
              bottom: null,
              width: 286.0,
              height: 49.0,
              child: GeneratedMpesaservicesWidget(),
            ),
            Positioned(
              left: 33.0,
              top: 256.0,
              right: null,
              bottom: null,
              width: 294.0,
              height: 44.0,
              child: GeneratedRectangle11Widget(),
            ),
            Positioned(
              left: 57.0,
              top: 265.0,
              right: null,
              bottom: null,
              width: 263.0,
              height: 30.0,
              child: GeneratedSendMoneyWidget(),
            ),
            Positioned(
              left: 30.0,
              top: 317.0,
              right: null,
              bottom: null,
              width: 293.0,
              height: 44.0,
              child: GeneratedRectangle12Widget(),
            ),
            Positioned(
              left: 41.0,
              top: 323.0,
              right: null,
              bottom: null,
              width: 288.0,
              height: 34.0,
              child: GeneratedWithdrawmoneyWidget(),
            ),
            Positioned(
              left: 30.0,
              top: 375.0,
              right: null,
              bottom: null,
              width: 297.0,
              height: 40.0,
              child: GeneratedRectangle13Widget(),
            ),
            Positioned(
              left: 51.0,
              top: 384.0,
              right: null,
              bottom: null,
              width: 279.0,
              height: 30.0,
              child: GeneratedBuyairtimeorbundlesWidget(),
            ),
            Positioned(
              left: 30.0,
              top: 434.0,
              right: null,
              bottom: null,
              width: 294.0,
              height: 40.0,
              child: GeneratedRectangle14Widget(),
            ),
            Positioned(
              left: 54.0,
              top: 439.0,
              right: null,
              bottom: null,
              width: 270.0,
              height: 26.0,
              child: GeneratedLoansandsavingsWidget(),
            ),
            Positioned(
              left: 30.0,
              top: 498.0,
              right: null,
              bottom: null,
              width: 294.0,
              height: 39.0,
              child: GeneratedRectangle15Widget(),
            ),
            Positioned(
              left: 54.0,
              top: 498.0,
              right: null,
              bottom: null,
              width: 268.0,
              height: 31.0,
              child: GeneratedLipanaMPesaWidget(),
            ),
            Positioned(
              left: 33.0,
              top: 556.0,
              right: null,
              bottom: null,
              width: 290.0,
              height: 36.0,
              child: GeneratedRectangle16Widget(),
            ),
            Positioned(
              left: 49.0,
              top: 556.0,
              right: null,
              bottom: null,
              width: 272.0,
              height: 35.0,
              child: GeneratedMyAccountWidget(),
            ),
            Positioned(
              left: 51.0,
              top: 597.0,
              right: null,
              bottom: null,
              width: 265.0,
              height: 33.0,
              child: GeneratedButtonWidget(),
            )
          ],
        ),
      ),
    ));
  }
}
